FROM registry.redhat.io/openshift4/ose-jenkins-agent-maven

User root

RUN dnf -y module enable container-tools:rhel8; dnf -y update; dnf -y reinstall shadow-utils; dnf -y install skopeo fuse-overlayfs; rm -rf /var/cache /var/log/dnf* /var/log/yum.*

# Adjust storage.conf to enable Fuse storage.
RUN sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' /etc/containers/storage.conf
RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock

# Set up environment variables to note that this is
# not starting with usernamespace and default to
# isolate the filesystem with chroot.
ENV _BUILDAH_STARTED_IN_USERNS="" BUILDAH_ISOLATION=chroot

User 1001

WORKDIR /tmp
RUN curl -o /tmp/helm-v3.7.0.tar.gz  https://get.helm.sh/helm-v3.7.0-rc.3-linux-amd64.tar.gz
RUN tar zxf /tmp/helm-v3.7.0.tar.gz
RUN cp /tmp/linux-amd64/helm /usr/bin/helm
RUN chmod +x /usr/bin/helm

RUN helm version
